server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.at.springcloud.entities   # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: microservicecloud-dept  #注册进eureka服务显示的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true    # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      test-while-idle: true
      validation-query: SELECT 1

# 日志的方式打印sql
logging:
  level:
    com.at.springcloud.mapper: DEBUG

#eureka客户端配置
eureka: #客户端注册进eureka服务列表内
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka #注册地址(单机)
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #注册地址(集群)
  instance:
    instance-id: microservicecloud-provider-dept-8001 #修改注册eureka 中Status 的显示名称
    prefer-ip-address: true     #鼠标移动到status名称上时可以显示IP地址

#显示/info信息
info:
  app.name: microservicecloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$